// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternating_text: dynamic(() => import("./AlternatingText")),
  big_message: dynamic(() => import("./BigMessage")),
  carousel: dynamic(() => import("./Carousel")),
  hero: dynamic(() => import("./Hero")),
  sky_dive: dynamic(() => import("./SkyDive")),
};
